# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cma-aks
image:
  repo: registry.gitlab.com/mvenezia/cma-aks:latest

port: 80
service:
  port: 80
  type: ClusterIP
ingress:
  rest:
    name: cma-aks
    host: cma-aks.ontario.cluster.cnct.io
  grpc:
    name: cma-aks-grpc
    host: cma-aks-grpc.ontario.cluster.cnct.io
issuer:
  email: mvenezia@gmail.com
  region: us-east-1
