# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: cma-aks
image:
   repo: quay.io/samsung_cnct/cma-aks:0.1.2
   pullPolicy: Always

port: 80
service:
   port: 80
   type: ClusterIP
ingress:
   rest:
      name: cma-aks
      host: cma-aks.ontario.cluster.cnct.io
   grpc:
      name: cma-aks-grpc
      host: cma-aks-grpc.ontario.cluster.cnct.io
issuer:
   email: someone@cnct.io
   region: us-east-1
   accesskey:
      id: ""
      secret: ""
   hostedzoneid: ""
